import { useState } from "react";
import { GlassCard } from "./GlassCard";
import { Lightbulb, Loader, AlertCircle, CheckCircle } from "lucide-react";
import { generateRevisionNotes } from "../../lib/ai-api";

interface AIRevisionCardProps {
  lessonTitle: string;
  description: string;
  transcript?: string;
}

export default function AIRevisionCard({
  lessonTitle,
  description,
  transcript,
}: AIRevisionCardProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [revision, setRevision] = useState<{
    summary?: string;
    key_points?: string[];
    quick_revision_notes?: string;
  } | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateRevision = async () => {
    setIsLoading(true);
    setError(null);
    setRevision(null);

    try {
      const result = await generateRevisionNotes(
        lessonTitle,
        description,
        transcript
      );

      if (result.error) {
        setError(result.error);
      } else {
        setRevision(result);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate revision notes");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-4 mt-6">
      {/* Revision Button */}
      {!revision && (
        <button
          onClick={handleGenerateRevision}
          disabled={isLoading}
          className="w-full px-6 py-3 bg-linear-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg font-semibold transition flex items-center justify-center gap-2"
        >
          {isLoading ? (
            <>
              <Loader className="h-5 w-5 animate-spin" />
              AI is thinking...
            </>
          ) : (
            <>
              <Lightbulb className="h-5 w-5" />
              Generate AI Revision Notes
            </>
          )}
        </button>
      )}

      {/* Error State */}
      {error && (
        <GlassCard className="p-4 border-2 border-red-500/50 bg-red-500/10">
          <div className="flex items-start gap-3">
            <AlertCircle className="h-5 w-5 text-red-400 shrink-0 mt-0.5" />
            <div>
              <p className="text-red-200 font-semibold">Error</p>
              <p className="text-red-100 text-sm">{error}</p>
              <button
                onClick={() => {
                  setError(null);
                  setRevision(null);
                }}
                className="mt-2 text-sm text-red-300 hover:text-red-200 underline"
              >
                Try Again
              </button>
            </div>
          </div>
        </GlassCard>
      )}

      {/* Revision Notes Display */}
      {revision && (
        <GlassCard className="p-6 space-y-6 border-2 border-blue-500/30 bg-blue-500/10">
          {/* Header */}
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-blue-500/20 rounded-lg">
                <Lightbulb className="h-5 w-5 text-blue-400" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-white">AI Revision Notes</h3>
                <p className="text-sm text-gray-400">Generated by AI Mentor</p>
              </div>
            </div>
            <button
              onClick={() => {
                setRevision(null);
                setError(null);
              }}
              className="text-gray-400 hover:text-gray-200 transition"
            >
              ✕
            </button>
          </div>

          {/* Summary */}
          {revision.summary && (
            <div className="border-l-4 border-blue-500 pl-4">
              <p className="text-sm text-gray-300 font-semibold mb-2">Summary</p>
              <p className="text-gray-100">{revision.summary}</p>
            </div>
          )}

          {/* Key Points */}
          {revision.key_points && revision.key_points.length > 0 && (
            <div className="border-l-4 border-purple-500 pl-4">
              <p className="text-sm text-gray-300 font-semibold mb-3">Key Points</p>
              <ul className="space-y-2">
                {revision.key_points.map((point, idx) => (
                  <li key={idx} className="flex items-start gap-3">
                    <CheckCircle className="h-4 w-4 text-green-400 mt-0.5 shrink-0" />
                    <span className="text-gray-100">{point}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Quick Revision Notes */}
          {revision.quick_revision_notes && (
            <div className="bg-white/5 rounded-lg p-4 border border-white/10">
              <p className="text-sm text-gray-300 font-semibold mb-3">Quick Revision</p>
              <div className="text-gray-100 whitespace-pre-wrap text-sm leading-relaxed">
                {revision.quick_revision_notes}
              </div>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex gap-3 pt-4 border-t border-white/10">
            <button
              onClick={() => {
                const text = `${revision.summary}\n\nKey Points:\n${revision.key_points?.join("\n")}\n\n${revision.quick_revision_notes}`;
                navigator.clipboard.writeText(text);
              }}
              className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-semibold transition text-sm"
            >
              Copy Notes
            </button>
            <button
              onClick={() => {
                setRevision(null);
                setError(null);
              }}
              className="flex-1 px-4 py-2 bg-gray-600 hover:bg-gray-500 text-white rounded-lg font-semibold transition text-sm"
            >
              Regenerate
            </button>
          </div>
        </GlassCard>
      )}
    </div>
  );
}
